@startuml

title MD de BEFIT

object User{
name
gender
age
height
weight
String[] gastronomyPreference
String[] frequencyPreference
}
object BEFIT{
}
Object Plan{

}

Object Eat{
calories
}

Object HomeEat{
}
Object OutdoorEat{
}
Object Restaurant{
ubication
}

Object Exercise{
totalMinutes
}

Object IndoorActivity{
numberActivity
}

Object Activity{
minutes
typeActivity
}

Object OutdoorActivity{
minutes
distance
}

Object WaterActivity{
minutes
}

Object Statistic{
BMI
calories
}

Object Time{
}

Object Ubication{

}

Object Factors{
Time
Statistic
Ubication
}
Object Cardio
Object Force
Object Dish

Exercise <|-down- IndoorActivity
Exercise <|-down- OutdoorActivity
Exercise <|-down- WaterActivity
Plan  <|-down-  Exercise
Plan  <|-down-  Eat
Eat  <|-down-  OutdoorEat
Eat  <|-down-  HomeEat
Activity  <|-down-  Cardio
Activity  <|-down-  Force

User "*" -left-o "1" BEFIT: logIn
BEFIT "1" *-- "1..*" Plan: contain
User "1" -- "1" Plan: realize
IndoorActivity "1" *-- "1..n" Activity: formBy
OutdoorEat "1" *-- "1..n" Restaurant: formBy
User "1" -- "1" Statistic: has
Statistic "1" -- "*" Exercise: calculatedBy
Statistic "1" -- "*" Eat: calculatedBy
Factors "1" -- "1" Plan: recommend
Factors "1" -up- "1" Time: formBy
Factors "1" -up- "1" Statistic: formBy
Factors "1" -up- "1" Ubication: formBy
Factors "1" -- "1" Eat: formBy
User "1" -- "1" Ubication: has
BEFIT "1" -- "1" Time: has
HomeEat "1" *-- "1..3" Dish: formBy


@enduml